replicaCount: 3


image:
  repository: 308172169369.dkr.ecr.eu-central-1.amazonaws.com/transfers
  pullPolicy: Always
  tag: "latest"


service:
  type: ClusterIP
  port: 9090
  targetPort: 9090

imagePullSecrets:
   - name: transfers-secret

resources: 
  limits:
     cpu: 1000m
     memory: 128Mi
  requests:
     cpu: 500m
     memory: 64Mi