apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: dev
  labels:
    app: gateway-svc
    environment: dev
    role: gateway
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: gateway-svc
    environment: dev
    role: gateway
    tier: frontend
