piVersion: apps/v1
kind: Service
metadata:
  name: backend
  labels:
    app: auth-svc
    environment: dev
spec:
  selector:
    app: auth-svc
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer