apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-backend-deployment
  labels:
    app: gateway-svc
    environment: dev
  
spec:
  selector:
    matchLabels:
      app: gateway-svc
      environment: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-svc
        environment: dev
    spec:
      containers:
      - name: gateway-svc
        image: maverickme22/gateway:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
        env:
          - name: AUTH_SERVICE_URL
            value: auth-backend-service:50051