apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: auth-gateway
    environment: dev
spec:
  selector:
    app: auth-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer