apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: dev
  labels:
    app: auth-svc
    environment: dev
    role: authService
    tier: backend
spec:
  ports:
    - port: 80
  selector:
    app: auth-svc
    environment: dev
    role: authService
    tier: backend
