apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kappa-backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maverickme22/test.git
    targetRevision: HEAD
    path: helm/example-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
